// Single source for legacy (old WordPress site) and duplicate-URL redirects.
// astro.config.mjs turns these into meta-refresh pages, writes real 301 rules
// to dist/.htaccess for Apache/Plesk, and warns when vercel.json drifts.

const langs = ['', '/ur', '/ar'];
const everyLang = (from, to) => langs.map((prefix) => [`${prefix}${from}`, `${prefix}${to}`]);

/** Page redirects: [from, to]. `from` matches with or without a trailing slash. */
export const pageRedirects = [
    // Old Urdu slugs
    ['/ur/قرآن-مجید-کے-لیے-عربی-فونٹ', '/ur/products/arabicfont'],
    ['/ur/قرآن-ایکسپلورر', '/ur/projects/quranexplorer'],
    ['/ur/ايزى-اردو-کی-بورڈ', '/ur/products/easyurdu'],
    ['/ur/امیجن', '/ur/projects/imagine'],
    ['/ur/کتابی', '/ur/products/kitabi'],
    ['/ur/نیشنل-ایلیئن-ریجسٹریشن-ایتھاریٹی-nara', '/ur/projects/nara-national-alien-registration-authority'],
    ['/ur/تعارف', '/ur/about-us'],
    ['/ur/قرآن-پرنٹنگ-کامپلیکس-پروجیکٹ', '/ur/projects/quran-printing-complex-project'],
    ['/ur/قرآن-پاک', '/ur/products/quran-pak'],
    ['/ur/قرآن-آڈیو', '/ur/quran-audio'],
    ['/ur/قرآن-مجید', '/ur/products/quran-majeed'],
    ['/ur/ایزی-سندھی-کی-بورڈ', '/ur/products/easysindhi'],

    // Old FAQ entries
    ['/ufaqs', '/faqs'],
    ['/ufaqs/how-can-i-change-adhan-alarm-notification', '/faqs'],
    ['/ufaqs/i-dont-have-credit-card-or-unable-to-own-credit-card-can-i-send-payment-to-your-bank-account-or-any-other-means-for-purchasing-the-full-version', '/faqs'],
    ['/ufaqs/i-purchased-full-version-on-my-iphone-but-now-it-is-showing-free-version-only-how-to-fix-this', '/faqs'],
    ['/ufaqs/how-to-pay-using-easy-paisa', '/faqs'],
    ['/ufaqs/how-to-add-a-bookmark', '/faqs'],
    ['/ufaqs/adhan-notifications-are-not-in-time-in-my-device', '/faqs'],
    ['/faq', '/faqs'],

    // Old short URLs and renamed pages
    ['/certificate', '/certificates'],
    ['/privacy', '/privacy-policy'],
    ['/terms', '/terms-and-conditions'],
    ['/quran-majeed', '/products/quran-majeed'],
    ['/easyurdu', '/products/easyurdu'],
    ['/kitabi', '/products/kitabi'],
    ['/engage-ai-pdms', '/engage-ai'],

    // Duplicate pages: one canonical URL each
    ...everyLang('/contact', '/contact-us'),
    ...everyLang('/nadra-software', '/projects/nadra-software'),
    ...everyLang('/nadra-citizens-database', '/projects/nadra-software'),
    ...everyLang('/projects/nadra-citizens-database', '/projects/nadra-software'),
];

/** Server-only redirects (files and targets a meta-refresh page cannot cover). */
export const serverRedirects = [
    ['/products/quran-tv', '/products#quran-tv'],
    ['/qm', '/wp-content/uploads/qm.jpg'],
    ['/sitemap_index.xml', '/sitemap-index.xml'],
    ['/page-sitemap.xml', '/sitemap-index.xml'],
    ['/ufaq-sitemap.xml', '/sitemap-index.xml'],
    ['/feed', '/'],
    ['/ur/feed', '/ur'],
    ['/ar/feed', '/ar'],
    ['/ufaqs/feed', '/faqs'],
];

export const allRedirects = [...pageRedirects, ...serverRedirects];

/** Astro `redirects` config: builds meta-refresh fallback pages. */
export const astroRedirects = Object.fromEntries(
    [...pageRedirects, ['/products/quran-tv', '/products#quran-tv']],
);

const escapeRegex = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Apache .htaccess: 301 rules, no trailing slash, directory index, 404 page. */
export const buildHtaccess = () => {
    const rules = allRedirects.map(
        ([from, to]) => `RewriteRule ^${escapeRegex(from.slice(1))}/?$ ${to} [R=301,L,NE]`,
    );
    return [
        '# Generated by astro.config.mjs from redirects.mjs. Do not edit.',
        'AddDefaultCharset UTF-8',
        'ErrorDocument 404 /404.html',
        'DirectorySlash Off',
        'Options -MultiViews',
        '',
        '<IfModule mod_rewrite.c>',
        'RewriteEngine On',
        '',
        '# Legacy redirects',
        ...rules,
        '',
        '# Remove trailing slashes (trailingSlash: never)',
        'RewriteCond %{REQUEST_URI} !^/$',
        'RewriteRule ^(.+)/$ /$1 [R=301,L]',
        '',
        '# Serve /page from /page/index.html',
        'RewriteCond %{REQUEST_FILENAME} !-f',
        'RewriteCond %{DOCUMENT_ROOT}/$1/index.html -f',
        'RewriteRule ^(.+)$ /$1/index.html [L]',
        '</IfModule>',
        '',
        '# Caching: pages and text files revalidate on every visit so deploys show up',
        '# immediately; hashed /_astro/ assets cache for a year; other images and fonts',
        '# for a week.',
        '<IfModule mod_headers.c>',
        '<FilesMatch "\\.(html|xml|txt|json)$">',
        '  Header set Cache-Control "no-cache"',
        '</FilesMatch>',
        '<If "%{REQUEST_URI} =~ m#^/_astro/#">',
        '  Header set Cache-Control "public, max-age=31536000, immutable"',
        '</If>',
        '<If "%{REQUEST_URI} !~ m#^/_astro/# && %{REQUEST_URI} =~ m#\\.(png|jpe?g|gif|webp|svg|ico|woff2?)$#">',
        '  Header set Cache-Control "public, max-age=604800"',
        '</If>',
        '</IfModule>',
        '',
    ].join('\n');
};

/**
 * vercel.json `redirects` entries. vercel.json sets trailingSlash: false, so
 * sources need no slash variant. Non-ASCII sources get upper- and lower-case
 * percent-encoding, because old links use both.
 */
export const buildVercelRedirects = () =>
    allRedirects.flatMap(([from, to]) => {
        const encoded = encodeURI(from);
        const sources = encoded === from ? [from] : [encoded, encoded.replace(/%[0-9A-F]{2}/g, (m) => m.toLowerCase())];
        return sources.map((source) => ({
            source,
            destination: encodeURI(to).replace(/%23/g, '#'),
            permanent: true,
        }));
    });
