import json
import os

files = {
    'en': 'src/i18n/en.json',
    'ur': 'src/i18n/ur.json',
    'ar': 'src/i18n/ar.json'
}

data_to_add = {
    'en': {
        "home.seo.title": "PDMS – Islamic Mobile Apps & Digital Solutions for Muslims Worldwide",
        "home.seo.desc": "Pakistan Data Management Services (PDMS) is a leading Islamic technology company developing Quran apps, prayer tools, Islamic digital platforms, and multilingual mobile solutions trusted by millions worldwide.",
        "home.metrics.downloads.suffix": "M+",
        "home.metrics.years.suffix": "+ Yrs",
        "home.metrics.apps.suffix": "+",
        "home.metrics.clients.suffix": "+",
        "home.mock.logo.title": "Quran Majeed",
        "home.mock.ayah.arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        "home.mock.ayah.trans": "In the name of Allah, the Entirely Merciful, the Especially Merciful.",
        "home.mock.stats.users": "100M+ Users",
        "home.mock.stats.apps": "50+ Apps",
        "home.floating.pasha.title": "PASHA Awards",
        "home.floating.pasha.desc": "Best Islamic Apps",
        "home.floating.eu.title": "EasyUrdu",
        "home.floating.eu.desc": "30M+ Installs",
        "home.partners.google": "Google Play",
        "home.partners.apple": "App Store",
        "home.partners.nadra": "NADRA",
        "home.partners.kfqc": "King Fahad Quran Complex",
        "home.partners.nara": "NARA Authority",
        "home.partners.pasha": "P@SHA",
        "home.products.qm.name": "Quran Majeed",
        "home.products.qm.tagline": "Flagship Application",
        "home.products.qm.desc": "The world's leading Quran application featuring Quran recitations, translations, tafsir, prayer timings, Qibla direction, Islamic content, and advanced learning tools trusted by millions globally.",
        "home.products.qm.badge": "Award Winner",
        "home.products.qm.f1": "World-renowned Quran reciters",
        "home.products.qm.f2": "Interactive translations & Tafsir",
        "home.products.qm.f3": "Visual Salah & Prayer alerts",
        "home.products.qm.f4": "Advanced Quran memorization aids",
        "home.products.qp.name": "Quran Pak",
        "home.products.qp.tagline": "Elegant Quran Reader",
        "home.products.qp.desc": "A simple and beautifully designed Quran reading experience focused on accessibility, clarity, and authentic Islamic content for users worldwide.",
        "home.products.qp.badge": "Most Popular",
        "home.products.qp.f1": "Clean mushaf-like layout",
        "home.products.qp.f2": "High-contrast reading modes",
        "home.products.qp.f3": "Offline reading support",
        "home.products.qp.f4": "Bookmark and note taking",
        "home.products.qt.name": "Quran TV",
        "home.products.qt.tagline": "Streaming Platform",
        "home.products.qt.desc": "An Islamic streaming platform offering Quran recitations, Islamic lectures, spiritual content, and educational videos for Muslims around the world.",
        "home.products.qt.badge": "Smart TV App",
        "home.products.qt.f1": "24/7 Live Islamic broadcast",
        "home.products.qt.f2": "High-definition video streaming",
        "home.products.qt.f3": "Kids Islamic learning series",
        "home.products.qt.f4": "Sermons & Tafsir series",
        "home.products.eu.name": "Easy Urdu Keyboard",
        "home.products.eu.tagline": "Utility & Multilingual",
        "home.products.eu.desc": "An award-winning Urdu keyboard designed to make Urdu typing faster, easier, and more accessible for millions of users globally.",
        "home.products.eu.badge": "PASHA Winner",
        "home.products.eu.f1": "Voice-to-text Urdu typing",
        "home.products.eu.f2": "Instant Urdu translation",
        "home.products.eu.f3": "Rich Urdu editor & status maker",
        "home.products.eu.f4": "Beautiful custom themes"
    },
    'ur': {
        "home.seo.title": "پی ڈی ایم ایس - دنیا بھر کے مسلمانوں کے لیے اسلامی موبائل ایپس اور ڈیجیٹل حل",
        "home.seo.desc": "پاکستان ڈیٹا مینجمنٹ سروسز (PDMS) ایک معروف اسلامی ٹیکنالوجی کمپنی ہے جو قرآن ایپس، نماز کے ٹولز، اسلامی ڈیجیٹل پلیٹ فارمز، اور کثیر اللسانی موبائل سلوشنز تیار کرتی ہے جن پر دنیا بھر کے لاکھوں لوگ بھروسہ کرتے ہیں۔",
        "home.metrics.downloads.suffix": "M+",
        "home.metrics.years.suffix": "+ سال",
        "home.metrics.apps.suffix": "+",
        "home.metrics.clients.suffix": "+",
        "home.mock.logo.title": "قرآن مجید",
        "home.mock.ayah.arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        "home.mock.ayah.trans": "اللہ کے نام سے جو بڑا مہربان نہایت رحم والا ہے۔",
        "home.mock.stats.users": "100M+ صارفین",
        "home.mock.stats.apps": "50+ ایپس",
        "home.floating.pasha.title": "پاشا ایوارڈز",
        "home.floating.pasha.desc": "بہترین اسلامی ایپس",
        "home.floating.eu.title": "ایزی اردو",
        "home.floating.eu.desc": "30M+ انسٹالز",
        "home.partners.google": "گوگل پلے",
        "home.partners.apple": "ایپ اسٹور",
        "home.partners.nadra": "نادرہ",
        "home.partners.kfqc": "کنگ فہد قرآن کمپلیکس",
        "home.partners.nara": "نارا اتھارٹی",
        "home.partners.pasha": "پاشا",
        "home.products.qm.name": "قرآن مجید",
        "home.products.qm.tagline": "فلیگ شپ ایپلیکیشن",
        "home.products.qm.desc": "دنیا کی معروف قرآنی ایپلی کیشن جس میں تلاوت قرآن، ترجمہ، تفسیر، نماز کے اوقات، قبلہ کی سمت، اسلامی مواد اور جدید سیکھنے کے ٹولز شامل ہیں جن پر دنیا بھر میں لاکھوں افراد بھروسہ کرتے ہیں۔",
        "home.products.qm.badge": "ایوارڈ یافتہ",
        "home.products.qm.f1": "دنیا کے مشہور قاریان قرآن",
        "home.products.qm.f2": "انٹرایکٹو ترجمہ اور تفسیر",
        "home.products.qm.f3": "بصری نماز اور نماز کے الرٹس",
        "home.products.qm.f4": "قرآن حفظ کرنے کے جدید ذرائع",
        "home.products.qp.name": "قرآن پاک",
        "home.products.qp.tagline": "خوبصورت قرآن ریڈر",
        "home.products.qp.desc": "دنیا بھر کے صارفین کے لیے قابل رسائی، وضاحت اور مستند اسلامی مواد پر مرکوز قرآن پڑھنے کا ایک سادہ اور خوبصورت ڈیزائن کردہ تجربہ۔",
        "home.products.qp.badge": "سب سے مشہور",
        "home.products.qp.f1": "مصحف کی طرح کا صاف لے آؤٹ",
        "home.products.qp.f2": "ہائی کنٹراسٹ ریڈنگ موڈز",
        "home.products.qp.f3": "آف لائن پڑھنے کی سہولت",
        "home.products.qp.f4": "بُک مارک اور نوٹ لینا",
        "home.products.qt.name": "قرآن ٹی وی",
        "home.products.qt.tagline": "اسٹریمنگ پلیٹ فارم",
        "home.products.qt.desc": "ایک اسلامی اسٹریمنگ پلیٹ فارم جو دنیا بھر کے مسلمانوں کے لیے تلاوت قرآن، اسلامی لیکچرز، روحانی مواد، اور تعلیمی ویڈیوز پیش کرتا ہے۔",
        "home.products.qt.badge": "اسمارٹ ٹی وی ایپ",
        "home.products.qt.f1": "24/7 لائیو اسلامی نشریات",
        "home.products.qt.f2": "ہائی ڈیفینیشن ویڈیو اسٹریمنگ",
        "home.products.qt.f3": "بچوں کے لیے اسلامی سیکھنے کی سیریز",
        "home.products.qt.f4": "خطبات اور تفسیر سیریز",
        "home.products.eu.name": "ایزی اردو کی بورڈ",
        "home.products.eu.tagline": "یوٹیلیٹی اور کثیر اللسانی",
        "home.products.eu.desc": "ایک ایوارڈ یافتہ اردو کی بورڈ جو اردو ٹائپنگ کو دنیا بھر کے لاکھوں صارفین کے لیے تیز، آسان اور قابل رسائی بنانے کے لیے ڈیزائن کیا گیا ہے۔",
        "home.products.eu.badge": "پاشا فاتح",
        "home.products.eu.f1": "آواز سے متن اردو ٹائپنگ",
        "home.products.eu.f2": "فوری اردو ترجمہ",
        "home.products.eu.f3": "بہترین اردو ایڈیٹر اور اسٹیٹس میکر",
        "home.products.eu.f4": "خوبصورت کسٹم تھیمز"
    },
    'ar': {
        "home.seo.title": "PDMS – تطبيقات الهاتف الإسلامية والحلول الرقمية للمسلمين حول العالم",
        "home.seo.desc": "خدمات إدارة البيانات الباكستانية (PDMS) هي شركة رائدة في التكنولوجيا الإسلامية تعمل على تطوير تطبيقات القرآن، وأدوات الصلاة، والمنصات الرقمية الإسلامية، والحلول المحمولة متعددة اللغات التي يثق بها الملايين حول العالم.",
        "home.metrics.downloads.suffix": "M+",
        "home.metrics.years.suffix": "+ سنوات",
        "home.metrics.apps.suffix": "+",
        "home.metrics.clients.suffix": "+",
        "home.mock.logo.title": "القرآن المجيد",
        "home.mock.ayah.arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        "home.mock.ayah.trans": "بسم الله الرحمن الرحيم",
        "home.mock.stats.users": "100M+ مستخدم",
        "home.mock.stats.apps": "50+ تطبيق",
        "home.floating.pasha.title": "جوائز PASHA",
        "home.floating.pasha.desc": "أفضل التطبيقات الإسلامية",
        "home.floating.eu.title": "EasyUrdu",
        "home.floating.eu.desc": "30M+ تثبيت",
        "home.partners.google": "جوجل بلاي",
        "home.partners.apple": "آب ستور",
        "home.partners.nadra": "نادرا",
        "home.partners.kfqc": "مجمع الملك فهد لطباعة المصحف الشريف",
        "home.partners.nara": "هيئة نارا",
        "home.partners.pasha": "باشا",
        "home.products.qm.name": "القرآن المجيد",
        "home.products.qm.tagline": "التطبيق الرائد",
        "home.products.qm.desc": "تطبيق القرآن الكريم الرائد في العالم الذي يضم تلاوات قرآنية وتراجم وتفسير ومواقيت الصلاة واتجاه القبلة ومحتوى إسلامي وأدوات تعليمية متقدمة يثق بها الملايين على مستوى العالم.",
        "home.products.qm.badge": "حائز على جائزة",
        "home.products.qm.f1": "قراء القرآن المشهورين عالمياً",
        "home.products.qm.f2": "تراجم تفاعلية وتفسير",
        "home.products.qm.f3": "صلاة مرئية وتنبيهات الصلاة",
        "home.products.qm.f4": "وسائل مساعدة متقدمة لحفظ القرآن",
        "home.products.qp.name": "القرآن باك",
        "home.products.qp.tagline": "قارئ قرآني أنيق",
        "home.products.qp.desc": "تجربة قراءة قرآنية بسيطة ومصممة بشكل جميل تركز على إمكانية الوصول والوضوح والمحتوى الإسلامي الأصيل للمستخدمين حول العالم.",
        "home.products.qp.badge": "الأكثر شهرة",
        "home.products.qp.f1": "تخطيط نظيف يشبه المصحف",
        "home.products.qp.f2": "أوضاع قراءة عالية التباين",
        "home.products.qp.f3": "دعم القراءة دون اتصال",
        "home.products.qp.f4": "إشارات مرجعية وتدوين الملاحظات",
        "home.products.qt.name": "تلفزيون القرآن",
        "home.products.qt.tagline": "منصة البث",
        "home.products.qt.desc": "منصة بث إسلامية تقدم تلاوات قرآنية ومحاضرات إسلامية ومحتوى روحي ومقاطع فيديو تعليمية للمسلمين حول العالم.",
        "home.products.qt.badge": "تطبيق التلفزيون الذكي",
        "home.products.qt.f1": "بث إسلامي حي على مدار 24 ساعة",
        "home.products.qt.f2": "بث فيديو عالي الدقة",
        "home.products.qt.f3": "سلسلة التعلم الإسلامي للأطفال",
        "home.products.qt.f4": "سلسلة الخطب والتفسير",
        "home.products.eu.name": "لوحة مفاتيح الأوردو السهلة",
        "home.products.eu.tagline": "أداة متعددة اللغات",
        "home.products.eu.desc": "لوحة مفاتيح أردية حائزة على جوائز صُممت لجعل الكتابة بالأردية أسرع وأسهل ويمكن الوصول إليها لملايين المستخدمين على مستوى العالم.",
        "home.products.eu.badge": "الفائز بجائزة PASHA",
        "home.products.eu.f1": "الكتابة بالأردية من الصوت إلى النص",
        "home.products.eu.f2": "ترجمة أردية فورية",
        "home.products.eu.f3": "محرر أردو غني وصانع حالات",
        "home.products.eu.f4": "ثيمات مخصصة جميلة"
    }
}

for lang, filepath in files.items():
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    data.update(data_to_add[lang])
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

print("JSON files updated successfully!")
