const fs = require('fs');
const path = require('path');

const i18nDir = path.join(__dirname, '../src/i18n');

function updateJson(file, data) {
  const filePath = path.join(i18nDir, file);
  const current = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  const updated = { ...current, ...data };
  fs.writeFileSync(filePath, JSON.stringify(updated, null, 2));
}

// ── ENGLISH ────────────────────────────────────────────────────────────────
const en = {
  // products page
  "products.hero.badge": "Our Ecosystem",
  "products.hero.title": "Innovative Digital Products",
  "products.hero.subtitle": "We build and maintain applications that inspire spiritual connections, facilitate native communication, and solve enterprise problems.",
  "products.tabs.all": "All Products",
  "products.tabs.islamic": "Islamic Apps",
  "products.tabs.webtv": "Web & TV Apps",
  "products.tabs.utility": "Utilities",
  "products.tabs.enterprise": "Enterprise Solutions",
  "products.support.title": "Need Technical Help With Our Apps?",
  "products.support.desc": "Visit our Support Center to read detailed FAQ guides on prayer alerts setup, subscription recovery, and adhan notification configurations.",
  "products.support.btn": "Go to Support & FAQ",
  "products.cta.title": "Looking for Enterprise Software Development?",
  "products.cta.desc": "We have designed and deployed national databases, citizen registries, and custom AI support models. Let's build your next digital product.",
  "products.cta.btn": "Get Free Consultation",

  // projects page
  "projects.hero.badge": "Case Studies",
  "projects.hero.title": "Our Projects & Case Studies",
  "projects.hero.subtitle": "Discover how we have partnered with government organizations, international publishers, and enterprise brands to build systems at scale.",
  "projects.deepdive.badge": "Technical Deep Dive",
  "projects.deepdive.title": "Case Study Details",
  "projects.deepdive.subtitle": "A look into the challenges, engineering solutions, and actual impact of our key project deliveries.",
  "projects.deepdive.challenge": "The Challenge",
  "projects.deepdive.solution": "Our Solution",
  "projects.deepdive.impact": "The Impact",
  "projects.cta.title": "Have a Custom Project in Mind?",
  "projects.cta.desc": "Let our decades of software engineering, custom mobile development, and systems design help your business build robust platforms.",
  "projects.cta.btn": "Start Your Project",

  // team page
  "team.hero.badge": "The Team",
  "team.hero.title": "Meet the People Behind PDMS",
  "team.hero.subtitle": "A dedicated team of engineers, designers, Islamic scholars, and product specialists working together since 1979.",
  "team.join.title": "Interested in Joining Our Team?",
  "team.join.desc": "We are always looking for talented engineers, designers, and product specialists who share our passion for meaningful technology.",
  "team.join.btn": "View Open Positions",

  // support page
  "support.hero.badge": "Support Center",
  "support.hero.title": "Help, FAQ & Technical Support",
  "support.hero.subtitle": "Find solutions for prayer notifications, restore premium purchases, or contact our customer support team directly.",
  "support.faq.title": "Frequently Asked Questions",
  "support.ticket.title": "Submit a Support Ticket",
  "support.ticket.subtitle": "Cannot find a solution in the FAQ? Send details directly to our technical support desk.",
  "support.ticket.name.label": "Your Name",
  "support.ticket.name.placeholder": "Enter your name",
  "support.ticket.email.label": "Email Address",
  "support.ticket.email.placeholder": "name@example.com",
  "support.ticket.app.label": "Select Application",
  "support.ticket.device.label": "Device Platform",
  "support.ticket.msg.label": "Describe the Issue",
  "support.ticket.msg.placeholder": "Describe what happens. Mention error codes or settings if applicable.",
  "support.ticket.btn": "Submit Ticket",
  "support.ticket.alert": "Thank you! Your support ticket has been sent. We will respond within 24 hours.",
  "support.urgent.title": "Urgent Support Issues",
  "support.urgent.desc": "If you are experiencing payment failures or represent an organization seeking support, you can mail our technical lead directly.",
  "support.urgent.btn": "Email Support: support@pakdata.com",

  // join / careers page
  "join.hero.badge": "Work With Us",
  "join.hero.title": "Build Technology That Makes a Meaningful Difference",
  "join.hero.subtitle": "Become part of a passionate team shaping the future of Islamic applications and localized mobile computing.",
  "join.hero.btn.openings": "View Open Positions",
  "join.hero.btn.benefits": "Why Join Us?",
  "join.benefits.badge": "Perks & Growth",
  "join.benefits.title": "What You'll Gain at PDMS",
  "join.benefits.subtitle": "We invest in our people's workspace, professional development, and long-term career growth.",
  "join.openings.badge": "Careers",
  "join.openings.title": "Current Opportunities",
  "join.openings.subtitle": "Explore exciting career opportunities and become part of our growing team.",
  "join.filter.all": "All Departments",
  "join.filter.engineering": "Engineering",
  "join.filter.creative": "Creative & Design",
  "join.filter.marketing": "Marketing",
  "join.filter.support": "Customer Support",
  "join.job.apply": "Apply Now",
  "join.modal.title": "Apply for Position",
  "join.modal.name.label": "Full Name",
  "join.modal.name.placeholder": "Enter your full name",
  "join.modal.email.label": "Email Address",
  "join.modal.email.placeholder": "name@example.com",
  "join.modal.phone.label": "Phone Number",
  "join.modal.phone.placeholder": "+92 300 1234567",
  "join.modal.resume.label": "Link to CV / Portfolio",
  "join.modal.resume.placeholder": "https://drive.google.com/your-cv-link",
  "join.modal.cover.label": "Brief Cover Note",
  "join.modal.cover.placeholder": "Why do you want to join PDMS?",
  "join.modal.btn": "Submit Application",
  "join.modal.alert": "Thank you! Your application has been successfully submitted to our HR team.",
  "join.hr.title": "Direct Recruitment Inquiries",
  "join.hr.desc": "Don't see an open role matching your skill set? You can send your resume, cover letter, and portfolio link directly to our human resources team.",
  "join.hr.btn": "Email: careers@pakdata.com",

  // privacy policy page
  "privacy.hero.badge": "Legal",
  "privacy.hero.title": "Privacy Policy",
  "privacy.hero.subtitle": "Our commitment to protecting your personal data and privacy across all our platforms and services.",

  // terms page
  "terms.hero.badge": "Legal",
  "terms.hero.title": "Terms & Conditions",
  "terms.hero.subtitle": "Please read these terms carefully before using our applications and services.",

  // footer
  "footer.nav.title": "Navigation",
  "footer.products.title": "Top Products",
  "footer.connect.title": "Stay Connected",
  "footer.connect.desc": "Subscribe to receive updates about our products, technology innovations, and news.",
  "footer.connect.placeholder": "Your email address",
  "footer.connect.business": "Business Inquiries:",
  "footer.copyright": "Pakistan Data Management Services. All rights reserved.",
  "footer.privacy": "Privacy Policy",
  "footer.terms": "Terms & Conditions"
};

// ── URDU ────────────────────────────────────────────────────────────────
const ur = {
  "products.hero.badge": "ہمارا ایکو سسٹم",
  "products.hero.title": "جدید ڈیجیٹل مصنوعات",
  "products.hero.subtitle": "ہم ایسی ایپلی کیشنز بناتے اور برقرار رکھتے ہیں جو روحانی تعلق کو متحرک کرتی ہیں، مادری زبان میں مواصلت کو آسان بناتی ہیں اور انٹرپرائز مسائل حل کرتی ہیں۔",
  "products.tabs.all": "تمام مصنوعات",
  "products.tabs.islamic": "اسلامی ایپس",
  "products.tabs.webtv": "ویب اور ٹی وی ایپس",
  "products.tabs.utility": "یوٹیلیٹیز",
  "products.tabs.enterprise": "انٹرپرائز حلول",
  "products.support.title": "ہماری ایپس کے ساتھ تکنیکی مدد کی ضرورت ہے؟",
  "products.support.desc": "نماز الرٹس سیٹ اپ، سبسکرپشن ریکوری، اور اذان نوٹیفیکیشن کنفیگریشنز کے بارے میں تفصیلی FAQ گائیڈز پڑھنے کے لیے ہمارے سپورٹ سینٹر پر جائیں۔",
  "products.support.btn": "سپورٹ اور FAQ پر جائیں",
  "products.cta.title": "انٹرپرائز سافٹ ویئر ڈویلپمنٹ کی تلاش ہے؟",
  "products.cta.desc": "ہم نے قومی ڈیٹا بیس، شہری رجسٹریاں، اور کسٹم AI سپورٹ ماڈل ڈیزائن اور تعینات کیے ہیں۔ آئیے آپ کی اگلی ڈیجیٹل پروڈکٹ بنائیں۔",
  "products.cta.btn": "مفت مشاورت حاصل کریں",

  "projects.hero.badge": "کیس اسٹڈیز",
  "projects.hero.title": "ہمارے پروجیکٹس اور کیس اسٹڈیز",
  "projects.hero.subtitle": "دریافت کریں کہ ہم نے سرکاری اداروں، بین الاقوامی پبلشرز، اور انٹرپرائز برانڈز کے ساتھ بڑے پیمانے پر سسٹم بنانے کے لیے کیسے شراکت داری کی۔",
  "projects.deepdive.badge": "تکنیکی گہرائی",
  "projects.deepdive.title": "کیس اسٹڈی کی تفصیلات",
  "projects.deepdive.subtitle": "ہمارے اہم پروجیکٹ ڈیلیوری کے چیلنجوں، انجینئرنگ حلوں، اور اصل اثرات پر ایک نظر۔",
  "projects.deepdive.challenge": "چیلنج",
  "projects.deepdive.solution": "ہمارا حل",
  "projects.deepdive.impact": "اثر",
  "projects.cta.title": "ذہن میں کوئی کسٹم پروجیکٹ ہے؟",
  "projects.cta.desc": "سافٹ ویئر انجینئرنگ، کسٹم موبائل ڈویلپمنٹ، اور سسٹمز ڈیزائن میں ہماری دہائیوں کی مہارت آپ کے کاروبار کو مضبوط پلیٹ فارم بنانے میں مدد کرے۔",
  "projects.cta.btn": "اپنا پروجیکٹ شروع کریں",

  "team.hero.badge": "ٹیم",
  "team.hero.title": "پی ڈی ایم ایس کے پیچھے موجود لوگوں سے ملیں",
  "team.hero.subtitle": "انجینئرز، ڈیزائنرز، اسلامی علماء، اور پروڈکٹ ماہرین کی ایک سرشار ٹیم جو 1979 سے مل کر کام کر رہی ہے۔",
  "team.join.title": "ہماری ٹیم میں شامل ہونے میں دلچسپی ہے؟",
  "team.join.desc": "ہم ہمیشہ باصلاحیت انجینئرز، ڈیزائنرز، اور پروڈکٹ ماہرین کی تلاش میں رہتے ہیں جو بامعنی ٹیکنالوجی کے لیے ہمارا جذبہ رکھتے ہوں۔",
  "team.join.btn": "کھلی آسامیاں دیکھیں",

  "support.hero.badge": "سپورٹ سینٹر",
  "support.hero.title": "مدد، FAQ اور تکنیکی سپورٹ",
  "support.hero.subtitle": "نماز نوٹیفیکیشنز کے حل تلاش کریں، پریمیم خریداری بحال کریں، یا براہ راست ہماری کسٹمر سپورٹ ٹیم سے رابطہ کریں۔",
  "support.faq.title": "اکثر پوچھے جانے والے سوالات",
  "support.ticket.title": "سپورٹ ٹکٹ جمع کریں",
  "support.ticket.subtitle": "FAQ میں حل نہیں ملا؟ تفصیلات براہ راست ہمارے تکنیکی سپورٹ ڈیسک کو بھیجیں۔",
  "support.ticket.name.label": "آپ کا نام",
  "support.ticket.name.placeholder": "اپنا نام درج کریں",
  "support.ticket.email.label": "ای میل ایڈریس",
  "support.ticket.email.placeholder": "name@example.com",
  "support.ticket.app.label": "ایپلی کیشن منتخب کریں",
  "support.ticket.device.label": "ڈیوائس پلیٹ فارم",
  "support.ticket.msg.label": "مسئلہ بیان کریں",
  "support.ticket.msg.placeholder": "بتائیں کیا ہوتا ہے۔ اگر لاگو ہو تو ایرر کوڈز یا سیٹنگز کا ذکر کریں۔",
  "support.ticket.btn": "ٹکٹ جمع کریں",
  "support.ticket.alert": "آپ کا شکریہ! آپ کا سپورٹ ٹکٹ بھیج دیا گیا ہے۔ ہم 24 گھنٹوں کے اندر جواب دیں گے۔",
  "support.urgent.title": "فوری سپورٹ مسائل",
  "support.urgent.desc": "اگر آپ ادائیگی میں ناکامی کا سامنا کر رہے ہیں یا آپ سپورٹ کے خواہاں کسی تنظیم کی نمائندگی کرتے ہیں تو آپ ہمارے تکنیکی سربراہ کو براہ راست ای میل کر سکتے ہیں۔",
  "support.urgent.btn": "ای میل سپورٹ: support@pakdata.com",

  "join.hero.badge": "ہمارے ساتھ کام کریں",
  "join.hero.title": "ایسی ٹیکنالوجی بنائیں جو بامعنی فرق پیدا کرے",
  "join.hero.subtitle": "اسلامی ایپلی کیشنز اور مقامی موبائل کمپیوٹنگ کے مستقبل کو تشکیل دینے والی ایک پرجوش ٹیم کا حصہ بنیں۔",
  "join.hero.btn.openings": "کھلی آسامیاں دیکھیں",
  "join.hero.btn.benefits": "ہمارے ساتھ کیوں؟",
  "join.benefits.badge": "مراعات اور ترقی",
  "join.benefits.title": "پی ڈی ایم ایس میں آپ کو کیا ملے گا",
  "join.benefits.subtitle": "ہم اپنے لوگوں کی ورک اسپیس، پیشہ ورانہ ترقی، اور طویل مدتی کیریئر کی ترقی میں سرمایہ کاری کرتے ہیں۔",
  "join.openings.badge": "کیریئر",
  "join.openings.title": "موجودہ مواقع",
  "join.openings.subtitle": "دلچسپ کیریئر کے مواقع دریافت کریں اور ہماری بڑھتی ہوئی ٹیم کا حصہ بنیں۔",
  "join.filter.all": "تمام محکمے",
  "join.filter.engineering": "انجینئرنگ",
  "join.filter.creative": "تخلیقی اور ڈیزائن",
  "join.filter.marketing": "مارکیٹنگ",
  "join.filter.support": "کسٹمر سپورٹ",
  "join.job.apply": "ابھی درخواست دیں",
  "join.modal.title": "پوزیشن کے لیے درخواست دیں",
  "join.modal.name.label": "پورا نام",
  "join.modal.name.placeholder": "اپنا پورا نام درج کریں",
  "join.modal.email.label": "ای میل ایڈریس",
  "join.modal.email.placeholder": "name@example.com",
  "join.modal.phone.label": "فون نمبر",
  "join.modal.phone.placeholder": "+92 300 1234567",
  "join.modal.resume.label": "CV / پورٹ فولیو کا لنک",
  "join.modal.resume.placeholder": "https://drive.google.com/your-cv-link",
  "join.modal.cover.label": "مختصر کور نوٹ",
  "join.modal.cover.placeholder": "آپ پی ڈی ایم ایس میں کیوں شامل ہونا چاہتے ہیں؟",
  "join.modal.btn": "درخواست جمع کریں",
  "join.modal.alert": "آپ کا شکریہ! آپ کی درخواست کامیابی کے ساتھ ہماری HR ٹیم کو بھیج دی گئی ہے۔",
  "join.hr.title": "براہ راست بھرتی کی انکوائریز",
  "join.hr.desc": "آپ کی مہارت سے ملتی جلتی کوئی کھلی آسامی نظر نہیں آ رہی؟ آپ اپنی CV، کور لیٹر اور پورٹ فولیو لنک براہ راست ہمارے انسانی وسائل کی ٹیم کو بھیج سکتے ہیں۔",
  "join.hr.btn": "ای میل: careers@pakdata.com",

  "privacy.hero.badge": "قانونی",
  "privacy.hero.title": "رازداری کی پالیسی",
  "privacy.hero.subtitle": "ہمارے تمام پلیٹ فارمز اور سروسز میں آپ کے ذاتی ڈیٹا اور رازداری کے تحفظ کے لیے ہمارا عزم۔",

  "terms.hero.badge": "قانونی",
  "terms.hero.title": "شرائط و ضوابط",
  "terms.hero.subtitle": "ہماری ایپلی کیشنز اور سروسز استعمال کرنے سے پہلے براہ کرم ان شرائط کو غور سے پڑھیں۔",

  "footer.nav.title": "نیوی گیشن",
  "footer.products.title": "اہم مصنوعات",
  "footer.connect.title": "جڑے رہیں",
  "footer.connect.desc": "ہماری مصنوعات، ٹیکنالوجی اختراعات، اور خبروں کے بارے میں اپڈیٹس حاصل کرنے کے لیے سبسکرائب کریں۔",
  "footer.connect.placeholder": "آپ کا ای میل ایڈریس",
  "footer.connect.business": "کاروباری انکوائریز:",
  "footer.copyright": "پاکستان ڈیٹا مینجمنٹ سروسز۔ جملہ حقوق محفوظ ہیں۔",
  "footer.privacy": "رازداری کی پالیسی",
  "footer.terms": "شرائط و ضوابط"
};

// ── ARABIC ────────────────────────────────────────────────────────────────
const ar = {
  "products.hero.badge": "نظامنا البيئي",
  "products.hero.title": "منتجات رقمية مبتكرة",
  "products.hero.subtitle": "نبني ونحافظ على تطبيقات تلهم التواصل الروحي وتسهل التواصل باللغة الأم وتحل مشاكل المؤسسات.",
  "products.tabs.all": "جميع المنتجات",
  "products.tabs.islamic": "التطبيقات الإسلامية",
  "products.tabs.webtv": "تطبيقات الويب والتلفزيون",
  "products.tabs.utility": "الأدوات",
  "products.tabs.enterprise": "حلول المؤسسات",
  "products.support.title": "هل تحتاج مساعدة تقنية مع تطبيقاتنا؟",
  "products.support.desc": "قم بزيارة مركز الدعم لدينا لقراءة أدلة FAQ التفصيلية حول إعداد تنبيهات الصلاة واستعادة الاشتراك وتكوينات إشعارات الأذان.",
  "products.support.btn": "اذهب إلى الدعم والأسئلة الشائعة",
  "products.cta.title": "هل تبحث عن تطوير برمجيات المؤسسات؟",
  "products.cta.desc": "لقد صممنا ونشرنا قواعد بيانات وطنية وسجلات مواطنين ونماذج دعم AI مخصصة. دعنا نبني منتجك الرقمي التالي.",
  "products.cta.btn": "احصل على استشارة مجانية",

  "projects.hero.badge": "دراسات الحالة",
  "projects.hero.title": "مشاريعنا ودراسات الحالة",
  "projects.hero.subtitle": "اكتشف كيف تشاركنا مع المنظمات الحكومية والناشرين الدوليين وعلامات المؤسسات التجارية لبناء أنظمة على نطاق واسع.",
  "projects.deepdive.badge": "التعمق التقني",
  "projects.deepdive.title": "تفاصيل دراسة الحالة",
  "projects.deepdive.subtitle": "نظرة على التحديات وحلول الهندسة والأثر الفعلي لعمليات التسليم الرئيسية لمشاريعنا.",
  "projects.deepdive.challenge": "التحدي",
  "projects.deepdive.solution": "حلنا",
  "projects.deepdive.impact": "الأثر",
  "projects.cta.title": "هل لديك مشروع مخصص في ذهنك؟",
  "projects.cta.desc": "دع عقودنا من هندسة البرمجيات وتطوير الجوال المخصص وتصميم الأنظمة تساعد عملك على بناء منصات قوية.",
  "projects.cta.btn": "ابدأ مشروعك",

  "team.hero.badge": "الفريق",
  "team.hero.title": "تعرف على الأشخاص وراء PDMS",
  "team.hero.subtitle": "فريق متفاني من المهندسين والمصممين وعلماء الإسلام وخبراء المنتجات يعملون معًا منذ عام 1979.",
  "team.join.title": "مهتم بالانضمام إلى فريقنا؟",
  "team.join.desc": "نحن دائمًا نبحث عن مهندسين ومصممين وخبراء منتجات موهوبين يشاركوننا شغفنا بالتكنولوجيا الهادفة.",
  "team.join.btn": "عرض المناصب المفتوحة",

  "support.hero.badge": "مركز الدعم",
  "support.hero.title": "المساعدة والأسئلة الشائعة والدعم الفني",
  "support.hero.subtitle": "ابحث عن حلول لإشعارات الصلاة، واستعد مشتريات الدفع المميزة، أو تواصل مع فريق دعم العملاء لدينا مباشرةً.",
  "support.faq.title": "الأسئلة الشائعة",
  "support.ticket.title": "تقديم تذكرة دعم",
  "support.ticket.subtitle": "لا يمكنك إيجاد حل في الأسئلة الشائعة؟ أرسل التفاصيل مباشرةً إلى مكتب الدعم الفني لدينا.",
  "support.ticket.name.label": "اسمك",
  "support.ticket.name.placeholder": "أدخل اسمك",
  "support.ticket.email.label": "عنوان البريد الإلكتروني",
  "support.ticket.email.placeholder": "name@example.com",
  "support.ticket.app.label": "اختر التطبيق",
  "support.ticket.device.label": "منصة الجهاز",
  "support.ticket.msg.label": "وصف المشكلة",
  "support.ticket.msg.placeholder": "صف ما يحدث. اذكر رموز الأخطاء أو الإعدادات إن أمكن.",
  "support.ticket.btn": "إرسال التذكرة",
  "support.ticket.alert": "شكرًا لك! تم إرسال تذكرة الدعم الخاصة بك. سنرد خلال 24 ساعة.",
  "support.urgent.title": "قضايا الدعم العاجل",
  "support.urgent.desc": "إذا كنت تعاني من فشل في الدفع أو تمثل منظمة تسعى للدعم، فيمكنك مراسلة قائدنا التقني مباشرةً.",
  "support.urgent.btn": "البريد الإلكتروني للدعم: support@pakdata.com",

  "join.hero.badge": "اعمل معنا",
  "join.hero.title": "ابنِ تكنولوجيا تُحدث فرقًا حقيقيًا",
  "join.hero.subtitle": "كن جزءًا من فريق متحمس يشكّل مستقبل التطبيقات الإسلامية والحوسبة المحمولة المحلية.",
  "join.hero.btn.openings": "عرض المناصب المفتوحة",
  "join.hero.btn.benefits": "لماذا تنضم إلينا؟",
  "join.benefits.badge": "المزايا والنمو",
  "join.benefits.title": "ما ستكسبه في PDMS",
  "join.benefits.subtitle": "نستثمر في مساحة عمل موظفينا وتطويرهم المهني ونمو مسيرتهم على المدى الطويل.",
  "join.openings.badge": "وظائف",
  "join.openings.title": "الفرص الحالية",
  "join.openings.subtitle": "استكشف فرص وظيفية مثيرة وكن جزءًا من فريقنا المتنامي.",
  "join.filter.all": "جميع الأقسام",
  "join.filter.engineering": "الهندسة",
  "join.filter.creative": "الإبداع والتصميم",
  "join.filter.marketing": "التسويق",
  "join.filter.support": "دعم العملاء",
  "join.job.apply": "تقدم الآن",
  "join.modal.title": "التقدم لمنصب",
  "join.modal.name.label": "الاسم الكامل",
  "join.modal.name.placeholder": "أدخل اسمك الكامل",
  "join.modal.email.label": "عنوان البريد الإلكتروني",
  "join.modal.email.placeholder": "name@example.com",
  "join.modal.phone.label": "رقم الهاتف",
  "join.modal.phone.placeholder": "+92 300 1234567",
  "join.modal.resume.label": "رابط السيرة الذاتية / المحفظة",
  "join.modal.resume.placeholder": "https://drive.google.com/your-cv-link",
  "join.modal.cover.label": "ملاحظة تغطية مختصرة",
  "join.modal.cover.placeholder": "لماذا تريد الانضمام إلى PDMS؟",
  "join.modal.btn": "إرسال الطلب",
  "join.modal.alert": "شكرًا لك! تم إرسال طلبك بنجاح إلى فريق الموارد البشرية لدينا.",
  "join.hr.title": "استفسارات التوظيف المباشر",
  "join.hr.desc": "لا ترى دورًا مفتوحًا يتناسب مع مهاراتك؟ يمكنك إرسال سيرتك الذاتية وخطاب التغطية ورابط المحفظة مباشرةً إلى فريق الموارد البشرية لدينا.",
  "join.hr.btn": "البريد الإلكتروني: careers@pakdata.com",

  "privacy.hero.badge": "قانوني",
  "privacy.hero.title": "سياسة الخصوصية",
  "privacy.hero.subtitle": "التزامنا بحماية بياناتك الشخصية وخصوصيتك عبر جميع منصاتنا وخدماتنا.",

  "terms.hero.badge": "قانوني",
  "terms.hero.title": "الشروط والأحكام",
  "terms.hero.subtitle": "يرجى قراءة هذه الشروط بعناية قبل استخدام تطبيقاتنا وخدماتنا.",

  "footer.nav.title": "التنقل",
  "footer.products.title": "أبرز المنتجات",
  "footer.connect.title": "ابق على تواصل",
  "footer.connect.desc": "اشترك لتلقي تحديثات حول منتجاتنا والابتكارات التكنولوجية والأخبار.",
  "footer.connect.placeholder": "عنوان بريدك الإلكتروني",
  "footer.connect.business": "استفسارات الأعمال:",
  "footer.copyright": "باكستان لخدمات إدارة البيانات. جميع الحقوق محفوظة.",
  "footer.privacy": "سياسة الخصوصية",
  "footer.terms": "الشروط والأحكام"
};

updateJson('en.json', en);
updateJson('ur.json', ur);
updateJson('ar.json', ar);

console.log('✅ All remaining page strings added to JSON files!');
